import { AlertCircle, FileText, Scale } from 'lucide-react';
import { FULL_DISCLAIMER_TEXT } from '../components/CalculatorDisclaimer';
import { Link } from 'react-router-dom';

export function Disclaimer() {
  return (
    <div className="flex flex-col flex-1 h-full w-full max-w-4xl mx-auto px-4 sm:px-6 md:px-8 py-6 sm:py-8 space-y-8">
      {/* Breadcrumbs */}
      <nav aria-label="Breadcrumb" className="text-xs font-bold uppercase tracking-widest text-[#8C7A6B] flex items-center gap-2">
        <Link to="/" className="hover:text-[#5A4633] transition-colors">Home</Link>
        <span className="text-[#DCD3C7]">&gt;</span>
        <span className="text-[#3D342C]" aria-current="page">Disclaimer</span>
      </nav>

      {/* Header */}
      <header className="border-b border-[#DCD3C7] pb-6">
        <div className="flex items-center gap-3 mb-3">
          <div className="bg-[#F9F7F4] p-2 text-[#5A4633] border border-[#DCD3C7] rounded-sm shrink-0">
            <Scale className="w-6 h-6" aria-hidden="true" />
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-[#42372E] tracking-tight font-serif italic">
            Disclaimer & Legal Notice
          </h1>
        </div>
        <p className="text-sm sm:text-base text-[#8C7A6B] max-w-3xl leading-relaxed mt-4">
          Please read this disclaimer carefully before using any tools, calculators, or estimators provided on this subdomain and the broader Rural Ops Tools network.
        </p>
      </header>

      <div className="bg-white border border-[#DCD3C7] p-6 md:p-8 rounded-sm shadow-sm space-y-6 text-[#42372E] mx-auto w-full">
        <h2 className="text-xl font-bold flex items-center gap-2 border-b border-[#DCD3C7] pb-3">
          <AlertCircle className="w-6 h-6 text-[#8C7A6B]" />
          Important Liability Notice
        </h2>
        
        <div className="prose prose-sm max-w-none text-[#5A4633]">
          <p className="leading-relaxed font-medium text-base">
            {FULL_DISCLAIMER_TEXT}
          </p>
          
          <h3 className="font-bold text-[#42372E] mt-6 mb-2">Scope of Tools</h3>
          <p className="leading-relaxed mb-4">
            This disclaimer applies selectively to all calculator, predictor, forecasting, and "what-if" modeling tools provided throughout the Rural Ops Tools ecosystem and its respective subdomains (including Wood Hub). Users assume full responsibility for decisions made using data generated by this software.
          </p>

          <h3 className="font-bold text-[#42372E] mt-6 mb-2">No Professional Advice</h3>
          <p className="leading-relaxed mb-4">
            The information and calculations are presented for educational and general planning purposes only. They do not constitute professional engineering, architectural, financial, legal, or agricultural advice. Always seek the advice of certified professionals within your local jurisdiction for specific operational, structural, or legal requirements.
          </p>

          <h3 className="font-bold text-[#42372E] mt-6 mb-2">Master Ecosystem Framework</h3>
          <p className="leading-relaxed">
            The policies detailed on our primary <a href="https://ruralopstools.com" className="font-bold underline hover:text-[#8C7A6B] transition-colors" target="_blank" rel="noopener noreferrer">Rural Ops Tools platform</a> site serve as the prevailing standard and source of truth for all terms of use, privacy issues, and intellectual property constraints. For the complete legal framework, please refer to the main organizational policies.
          </p>
        </div>
      </div>
    </div>
  );
}
