import { Layout } from '../components/Layout';
import { ShieldAlert, BookOpen, AlertCircle, Scale, FileText } from 'lucide-react';
import { FULL_DISCLAIMER_TEXT } from '../components/CalculatorDisclaimer';

export function DisclaimerPage() {
  return (
    <div className="max-w-3xl space-y-8 px-6 md:px-8 py-8 w-full mx-auto">
      <div className="border-b border-[#DCD3C7] pb-4">
        <h1 className="text-3xl font-extrabold text-[#42372E] tracking-tight flex items-center gap-3 font-serif italic">
          <FileText className="w-8 h-8 text-[#5A4633]" />
          Disclaimer & Legal Notice
        </h1>
      </div>
      
      <div className="bg-white border border-[#DCD3C7] p-6 rounded-sm shadow-sm space-y-4 text-[#42372E] mx-auto">
        <h2 className="text-lg font-bold flex items-center gap-2">
          <AlertCircle className="w-5 h-5 mx-1 text-[#8C7A6B]" />
          Important Liability Notice
        </h2>
        <p className="leading-relaxed font-medium">
          {FULL_DISCLAIMER_TEXT}
        </p>
        <p className="leading-relaxed text-sm text-[#8C7A6B] mt-4 pt-4 border-t border-[#DCD3C7]">
          This disclaimer applies selectively to all calculator, predictor, forecasting, and "what-if" modeling tools provided throughout the Rural Utility Cost ecosystem and its respective subdomains. Users assume full responsibility for decisions made using data generated by this software.
        </p>
      </div>

      <div className="space-y-4 text-[#8C7A6B] text-sm">
        <h3 className="font-bold text-lg text-[#42372E]">Master Ecosystem Framework</h3>
        <p>The policies detailed on our primary <a href="https://ruralutilitycost.com" className="underline hover:text-[#5A4633]">Rural Utility Cost</a> site serve as the prevailing standard and source of truth for all terms of use, privacy issues, and intellectual property constraints.</p>
      </div>
    </div>
  );
}

export function About() {
  return (
    <div className="max-w-3xl px-6 md:px-8 py-8 w-full mx-auto">
      <div className="flex items-center gap-3 mb-6 border-b border-[#DCD3C7] pb-4">
        <BookOpen className="w-8 h-8 text-[#5A4633]" />
        <h1 className="text-3xl font-extrabold text-[#42372E] tracking-tight font-serif italic">About Wood Hub</h1>
      </div>
      
      <div className="text-[#8C7A6B] space-y-6">
        <p className="text-lg leading-relaxed font-medium text-[#42372E]">
          The Wood app is a specialized subsystem of the <strong className="text-[#5A4633]">Rural Utility Cost</strong> master ecosystem. It serves as the dedicated lumber, timber, and woodworking hub for rural and agricultural users.
        </p>
        
        <div className="bg-white border text-sm border-[#DCD3C7] p-6 shadow-[0_1px_2px_rgba(0,0,0,0.02)] mt-8 rounded-sm">
          <h2 className="text-xl font-bold text-[#42372E] mt-0 flex items-center gap-2 mb-4">
            <ShieldAlert className="w-5 h-5 text-[#5A4633]" />
            Core Mission & Compliance LEDGER
          </h2>
          <p>
            Our core mission is to help woodworkers, sawmill operators, timber owners, contractors, and homesteaders make practical wood-related decisions relying on clean, technically accurate estimators.
          </p>
          <p className="mt-4">
            Every calculation presented through our tooling acts as a rigorous formal record in your estimation process, streamlining board feet calculations, kiln drying verifications, and yield constraints.
          </p>
        </div>
      </div>
    </div>
  );
}

export function Contact() {
  return (
    <div className="max-w-3xl px-6 md:px-8 py-8 w-full mx-auto">
      <h1 className="text-3xl font-extrabold text-[#42372E] font-serif italic tracking-tight mb-6 border-b border-[#DCD3C7] pb-4">Contact System Administration</h1>
      <p className="text-[#8C7A6B] mb-8 leading-relaxed">
        For inquiries regarding estimator tools, logic validation, or ecosystem integrations under the Rural Utility Cost umbrella, please utilize the formal support channels listed below.
      </p>
      
      <div className="bg-white border border-[#DCD3C7] p-8 rounded-sm shadow-[0_1px_2px_rgba(0,0,0,0.02)]">
        <h3 className="font-bold text-lg mb-2 text-[#42372E]">Direct Support Registry</h3>
        <p className="text-[#8C7A6B] mb-6 text-sm">Response times align with standard administrative SLAs (24-48 business hours).</p>
        <form className="space-y-4" onSubmit={e => e.preventDefault()}>
          <div>
            <label className="block text-xs font-bold uppercase tracking-wider text-[#8C7A6B] mb-1">Entity / Name</label>
            <input type="text" className="w-full border border-[#DCD3C7] p-2.5 text-sm bg-[#FAF7F2] text-[#3D342C] focus:border-[#5A4633] focus:ring-1 focus:ring-[#5A4633] outline-none transition" placeholder="e.g. Acme Sawmills" />
          </div>
          <div>
            <label className="block text-xs font-bold uppercase tracking-wider text-[#8C7A6B] mb-1">Return Transmission Address (Email)</label>
            <input type="email" className="w-full border border-[#DCD3C7] p-2.5 text-sm bg-[#FAF7F2] text-[#3D342C] focus:border-[#5A4633] focus:ring-1 focus:ring-[#5A4633] outline-none transition" placeholder="admin@domain.com" />
          </div>
          <div>
            <label className="block text-xs font-bold uppercase tracking-wider text-[#8C7A6B] mb-1">Inquiry / Ledger Data</label>
            <textarea className="w-full border border-[#DCD3C7] p-2.5 text-sm bg-[#FAF7F2] text-[#3D342C] min-h-[120px] focus:border-[#5A4633] focus:ring-1 focus:ring-[#5A4633] outline-none transition" placeholder="State your inquiry constraint..." />
          </div>
          <button className="bg-[#5A4633] text-white px-6 py-2 shadow-sm transition hover:bg-opacity-90 rounded-sm font-bold w-full sm:w-auto mt-4 text-sm">
            Transmit Inquiry
          </button>
        </form>
      </div>
    </div>
  );
}

export function Legal() {
  return (
    <div className="max-w-3xl space-y-8 px-6 md:px-8 py-8 w-full mx-auto">
      <div className="border-b border-[#DCD3C7] pb-4">
        <h1 className="text-3xl font-extrabold text-[#42372E] tracking-tight flex items-center gap-3 font-serif italic">
          <Scale className="w-8 h-8 text-[#5A4633]" />
          Legal & Compliance
        </h1>
      </div>
      
      <div className="bg-red-50 border border-red-200 p-6 rounded-sm shadow-sm space-y-4 text-red-900 mx-auto">
        <h2 className="text-lg font-bold flex items-center gap-2">
          <AlertCircle className="w-5 h-5 mx-1 text-red-700" />
          Mandatory Disclaimer
        </h2>
        <p className="leading-relaxed font-medium">
          Calculator results provided within the Wood Hub (and the broader Rural Utility Cost ecosystem) are <strong>estimates and decision support tools only</strong>. 
        </p>
        <p className="leading-relaxed text-sm">
          They are not certified engineering structural assessments or legally binding quotations. Users must verify all important decisions, dimensional requirements, yield forecasts, and financial models independently with certified professionals (e.g. licensed structural engineers, certified graders).
        </p>
      </div>

      <div className="space-y-4 text-[#8C7A6B] text-sm">
        <h3 className="font-bold text-lg text-[#42372E]">Ecosystem Framework</h3>
        <p>The policies detailed on the primary Rural Utility Cost master site serve as the prevailing standard and source of truth for terms of use, data privacy, and intellectual property. No conflicting brand or legal language exists on this subdomain application.</p>
      </div>
    </div>
  );
}

export function License() {
  return (
    <div className="max-w-3xl space-y-6 px-6 md:px-8 py-8 w-full mx-auto">
      <h1 className="text-3xl font-extrabold text-[#42372E] tracking-tight mb-6 border-b border-[#DCD3C7] pb-4 font-serif italic">Ecosystem License</h1>
      <p className="text-[#8C7A6B] leading-relaxed">
        The Rural Utility Cost application software and strictly related documentation (including the Wood Hub submodule) are issued under standard operational licensing terms designed for rural and agricultural enablement tools.
      </p>
      <div className="bg-[#F9F7F4] p-6 border border-[#DCD3C7] font-mono text-xs text-[#8C7A6B] rounded-sm overflow-x-auto shadow-sm">
        <pre>
          MIT License{'\n\n'}
          Copyright (c) {new Date().getFullYear()} Rural Utility Cost{'\n\n'}
          Permission is hereby granted, free of charge, to any person obtaining a copy{'\n'}
          of this software and associated documentation files (the "Software"), to deal{'\n'}
          in the Software without restriction, including without limitation the rights{'\n'}
          to use, copy, modify, merge, publish, distribute, sublicense, and/or sell{'\n'}
          copies of the Software, and to permit persons to whom the Software is{'\n'}
          furnished to do so, subject to the following conditions:{'\n\n'}
          The above copyright notice and this permission notice shall be included in all{'\n'}
          copies or substantial portions of the Software.{'\n\n'}
          THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR{'\n'}
          IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,{'\n'}
          FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
        </pre>
      </div>
    </div>
  );
}
